# Generated by Django 4.0.5 on 2023-02-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('Price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.FileField(upload_to='product_image')),
            ],
        ),
    ]
